version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jyu617/piper
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/mattn/goveralls
      - run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt ./...
      - run: goveralls -coverprofile=coverage.txt -service=circle-ci -repotoken=$COVERALLS_REPO_TOKEN