version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jyu617/piper
    steps:
      - checkout
      - run: go get -v -t -d ./...
  test:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u github.com/mattn/goveralls
      - run: go test -v -covermode=count -coverprofile=count.out ./...
      - run: goveralls -coverprofile=coverage.txt -service=circle-ci -repotoken=$COVERALLS_TOKEN || true
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build